In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/MyDrive/Dataset/nm4.csv"
path2 = "/content/drive/MyDrive/Dataset/m4t.csv"


dataframe = pd.read_csv(path)
dft = pd.read_csv(path2)


Mounted at /content/drive


In [4]:
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

k = 1
knn_classifier = KNeighborsClassifier(n_neighbors=k)
dt_classifier = tree.DecisionTreeClassifier()
svc_classifier = svm.SVC()
lr_classifier = LinearRegression()
ram_dt_classifier = RandomForestClassifier()
gnb_classifier = GaussianNB()

In [5]:
test=dataframe.to_numpy()
ob = dft.to_numpy()

X = test[:, 0:12] 
y = test[:, 11]
x_train, x_test,y_train, y_test = train_test_split(X, y,test_size=0.2,random_state = 42)
print(X.shape)
print(y.shape)

(399, 12)
(399,)


In [8]:
knn_classifier.fit(x_train, y_train)
knn_y_pred = knn_classifier.predict(x_train)

ram_dt_classifier.fit(x_train, y_train)
ran_dt_y_pred = ram_dt_classifier.predict(x_train)

gnb_classifier.fit(x_train, y_train)
gnb_y_pred = gnb_classifier.predict(x_train)

svc_classifier.fit(x_train, y_train)
svc_y_pred = svc_classifier.predict(x_train)

dt_classifier.fit(x_train, y_train)
dt_y_pred = dt_classifier.predict(x_train)

In [11]:
from sklearn.metrics import confusion_matrix
print("Depression")
print("\t")
print("knn")
print(confusion_matrix(knn_y_pred, y_train))
print("\t")
print("ram")
print(confusion_matrix(ran_dt_y_pred, y_train))
print("\t")
print("gnb")
print(confusion_matrix(gnb_y_pred, y_train))
print("\t")
print("svc")
print(confusion_matrix(svc_y_pred, y_train))
print("\t")
print("dt")
print(confusion_matrix(dt_y_pred, y_train))


Depression
	
knn
[[296   0]
 [  0  23]]
	
ram
[[296   0]
 [  0  23]]
	
gnb
[[296   0]
 [  0  23]]
	
svc
[[296  14]
 [  0   9]]
	
dt
[[296   0]
 [  0  23]]


In [12]:
test=dataframe.to_numpy()
ob = dft.to_numpy()

X = test[:, 0:13] 
y = test[:, 12]
x_train, x_test,y_train, y_test = train_test_split(X, y,test_size=0.2,random_state = 42)


In [13]:
from sklearn.metrics import confusion_matrix
print("Anxiety")
print("\t")
print("knn")
print(confusion_matrix(knn_y_pred, y_train))
print("\t")
print("ram")
print(confusion_matrix(ran_dt_y_pred, y_train))
print("\t")
print("gnb")
print(confusion_matrix(gnb_y_pred, y_train))
print("\t")
print("svc")
print(confusion_matrix(svc_y_pred, y_train))
print("\t")
print("dt")
print(confusion_matrix(dt_y_pred, y_train))


Anxiety
	
knn
[[285  11]
 [ 18   5]]
	
ram
[[285  11]
 [ 18   5]]
	
gnb
[[285  11]
 [ 18   5]]
	
svc
[[297  13]
 [  6   3]]
	
dt
[[285  11]
 [ 18   5]]


In [20]:
test=dataframe.to_numpy()
ob = dft.to_numpy()

X = test[:, 0:14] 
y = test[:, 13]
x_train, x_test,y_train, y_test = train_test_split(X, y,test_size=0.2,random_state = 42)

In [21]:
print(X)
print(y)

[[1 3 4 ... 1 0 0]
 [7 2 3 ... 0 0 0]
 [7 3 3 ... 0 0 0]
 ...
 [3 2 3 ... 0 0 0]
 [2 4 3 ... 0 0 0]
 [2 4 3 ... 0 0 0]]
[0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0
 0 1 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0]


In [22]:
from sklearn.metrics import confusion_matrix
print("Stress")
print("\t")
print("knn")
print(confusion_matrix(knn_y_pred, y_train))
print("\t")
print("ram")
print(confusion_matrix(ran_dt_y_pred, y_train))
print("\t")
print("gnb")
print(confusion_matrix(gnb_y_pred, y_train))
print("\t")
print("svc")
print(confusion_matrix(svc_y_pred, y_train))
print("\t")
print("dt")
print(confusion_matrix(dt_y_pred, y_train))

Stress
	
knn
[[279  17]
 [ 11  12]]
	
ram
[[279  17]
 [ 11  12]]
	
gnb
[[279  17]
 [ 11  12]]
	
svc
[[288  22]
 [  2   7]]
	
dt
[[279  17]
 [ 11  12]]


In [26]:
ser = pd.Series(pd.Categorical(['a', 'b', 'a']))
a=ser.to_numpy()
print(ser)
print("\t")
print(a)

0    a
1    b
2    a
dtype: category
Categories (2, object): ['a', 'b']
	
['a' 'b' 'a']
